sudo: required

language: elixir
elixir:
  - 1.6.5

services:
  - docker

install:
  - docker-compose build mssqlex

script:
  - docker-compose run mssqlex

after_script:
  - mix local.hex --force
  - mix local.rebar --force
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
